language: ruby
rvm:
- ruby-head
deploy:
  provider: heroku
  app: sheltered-cliffs-62363
  api_key:
    secure: IEl9z19y5ZiRCrZz0QUuVYB3ssMz/SxSqy/vHa5i2IzgUDGv8HQvYdOmF0HrrgFACacoRzh/2b/j6nIbiSkZr8mXJ8fl6iY5NMBnOgw9XYMGtvbJ0eqktsvxD+3LqJJ2Uy6wtd4MWc9CM+oM3hS1B8razHS1ylPdXVet/02cWwEgPU0XiZ5V3/s/r3GQA/3PROMf6hborzLrNB49NFG1D+cmy0KGZoVGNjIsYl9m9+haKnAoEhfgq3QuSu9eIYo7mRGhpanXS54T4ew3HAMtHh3Qqu2Mkm2OMUB9L/y/XpcgxWfHysZ5DqGgE2VF+wyFwtJrcYBtDrZeV0qyyJtQd9EUjQip0G8bMec6SYq6hRwXmU75u6vpVJRvsMybafwZlKgxSnfLuOPMHdt9OlpV6QxNUZa2iQO8rm91a5M+5ZOKL1wIgSMVj+CTtyCKbiFkN+VTsGBw3KQKmiE2EoFXHqPM/fs18nQiV1xhmsbg8V0fJhqii/3G6ub9xSIEarRClFuqCxCrCNAl+P+Bmv30pRPkZNlbMgAl01dqOwMkBbubi/YyvqxsOxOlcaHc1itXEff4eHO/LiM8+jztChXzT6PDfUAJXEavQSXx1CKjbkKjKnW0f75VM2YZZyJgiToTAzGPfyXTabSpCTJGk/2iefvyZ2sFvEoqFf7MEPKEPUA=
